[project]
name = "api_service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "httpx>=0.28.1",
    "minio>=7.2.16",
    "sqlalchemy",
    "starlette",
]
