[project]
name = "celery_workers"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "celery",
    "minio",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
    "qdrant-client",
    "pydantic-settings",
    "redis"
]
